from typing import Any, Protocol

from app.shared.schemas import MemoryEntry, SessionState


class IMemoryService(Protocol):
    def get_session_state(self, session_id: str) -> SessionState: ...
    def append_message(self, session_id: str, entry: MemoryEntry) -> None: ...
    def clear_session(self, session_id: str) -> bool: ...
    def close(self) -> None: ...


class IToolRegistry(Protocol):
    def resolve(self, tool_id: str) -> Any: ...
    def get_tools_for_openai(self) -> list[dict[str, object]]: ...
    def list_tools(self) -> list[str]: ...
